language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - tools
    - build-tools-25.0.2

    - android-25
    - extra-android-m2repository
  licenses:
      - 'android-sdk-license-5be876d5'
      - 'android-sdk-license-c81a61d9'